import {
  AlertTriangle,
  BadgeAlert,
  BadgeDollarSign,
  Baby,
  CalendarX2,
  CreditCard,
  Database,
  Globe,
  Hotel,
  Lock,
  Luggage,
  Mail,
  MapPin,
  MapPinned,
  Monitor,
  Phone,
  Plane,
  PlaneTakeoff,
  Shield,
  ShieldCheck,
  Ticket,
  UserRound,
  Wallet,
  WandSparkles,
  Waves,
} from 'lucide-react';

const ICONS = {
  'alert-triangle': AlertTriangle,
  baby: Baby,
  'badge-alert': BadgeAlert,
  'badge-dollar-sign': BadgeDollarSign,
  'calendar-x-2': CalendarX2,
  'credit-card': CreditCard,
  database: Database,
  globe: Globe,
  hotel: Hotel,
  lock: Lock,
  luggage: Luggage,
  mail: Mail,
  'map-pin': MapPin,
  'map-pinned': MapPinned,
  monitor: Monitor,
  phone: Phone,
  plane: Plane,
  'plane-takeoff': PlaneTakeoff,
  shield: Shield,
  'shield-check': ShieldCheck,
  ticket: Ticket,
  'user-round': UserRound,
  wallet: Wallet,
  'wand-sparkles': WandSparkles,
  waves: Waves,
};

export default function LucideIcon({ name, ...props }) {
  const Icon = ICONS[name];
  return Icon ? <Icon aria-hidden="true" {...props} /> : null;
}
